repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: mixed-line-ending
      args: ['--fix=lf']
      description: Forces to replace line ending by the UNIX 'lf' character.
    - id: pretty-format-json
      files: \.json$
      args: ['--autofix', '--no-sort-keys', '--no-ensure-ascii']
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/d-ryzhykau/pipenv-lock-pre-commit
  rev: 0.5.0
  hooks:
    - id: pipenv-lock
    - id: pipenv-verify
    - id: pipenv-requirements
    - id: pipenv-requirements-dev
