language: python
sudo: required
dist: focal
python:
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
install:
  - pip install ".[test]" .
script: pytest --cov=./vyper
after_success:
  - codecov
